/*
  Real customer reviews from facebook.com/kknottllc (source: "Facebook", the
  default if omitted) and the K. Knott, LLC Google Business listing
  (source: "Google": the 5.0-star / 25-review listing at Highway T,
  Excello, MO. There is a second, unrelated-looking "K. Knott LLC Tree
  Services and Stump Grinding" listing at 3.0 stars that appears to be a
  duplicate GBP and should NOT be used as a source. See project README.)
  To add a new one: copy an object below, fill in name/date/text, done.
  No build step, just save and refresh.
*/
window.KNOTTS_REVIEWS = [
  { name: "Shelby Ayers", date: "August 2026", text: `Knott's Tree Service is fast, reliable, and friendly! They do great work at a great price! Highly recommend!` },
  { name: "Lee Taylor", date: "2025", source: "Google", text: `100% recommend Knott's tree service! They were above and beyond professional! Kaleb came out to give us a free quote, kept in touch with me, and made sure my property was respected as it was his own. Very reasonable on the price as well. Great big thank you to him and his crew!` },
  { name: "Julie Green", date: "July 2026", text: `Kaleb and his crew have removed a few trees for us on a couple of properties. They are timely, do a great job & clean up when finished. Highly recommend - thank you Kaleb!!` },
  { name: "Julie M Whitt", date: "July 2026", text: `We highly recommend! This group of young men work together as a TEAM and get the job done quickly. All of them very efficient in their job. They clean-up and you hardly know they were there. Great job!` },
  { name: "April Roberts", date: "June 2026", text: `Your crew did an amazing job cutting down our tree and removing it last week! Fast, friendly and affordable! Thank you!` },
  { name: "Seton Paige", date: "June 2026", text: `I highly recommend reaching out to Kaleb! From the start, he was honest and transparent about what to expect, keeping me informed of any potential challenges along the way. He also took the time to provide important information I never would have thought to ask about, such as insurance coverage and workers' compensation policies, which gave me added peace of mind.` },
  { name: "Ashley Nolte", date: "June 2026", text: `Kaleb and his crew had awesome communication!! Always keeping me up to date what was happening etc. Also very fast!! 10/10 recommend!` },
  { name: "Avery Lambeth", date: "May 2026", text: `We contacted them and they were out the next day! They all worked so well together and completed the job wonderfully!` },
  { name: "Heather Lampkin", date: "May 2026", text: `Him and his crew did an amazing job!! They was there when said they would be and most of all saved us money!!! 10/10` },
  { name: "Jessica Nickerson-O'Guinn", date: "April 2026", text: `Knotts tree service did an amazing job cutting my parents tree down and helping them clear their garage roof. They were professional and I appreciate their time and hard work. Great job K.Knotts` },
  { name: "Cameron Shaw", date: "April 2026", text: `They responded quickly, took time to come give a FREE estimate, and not only did a great clean job, but even hauled the logs of the tree they cut down to my burn pile for me. Couldn't have asked for a better crew. They were extremely easy to work with!` },
  { name: "Paul DeMarco", date: "April 2026", text: `I highly recommend Kaleb! Him and his crew are truly masters of their art! I went to work in the morning and came home to a completely different property! If you need tree services make them your first call! You will not regret it!` },
  { name: "Steven Scherbring", date: "March 2026", text: `I had a tree over powerlines and a fence. They did a very nice job. Very professional and friendly. Definitely recommend.` },
  { name: "Nick Barnett", date: "March 2026", text: `Kaleb and his crew did a fantastic job cutting our dead ash tree down! Can't recommend highly enough.` },
  { name: "Jennifer Barnett", date: "March 2026", text: `We had K.Knott come and cut down our tree in the front that died due to the cicadas a couple years ago. His crew did a great job cutting, and cleaning up the mess tree cutting can cause. They also took out a stump that was from an old tree too! Thank you K.Knott!` },
  { name: "Donna Oberto Mefford", date: "February 2026", text: `Kaleb's guys came and cleaned up a huge brush pile and hauled it off. Price was great, he came when he said he would, guys were very polite and didn't leave tracks or brush in my yard. He is also a great neighbor.` },
  { name: "Alyssa Hart", date: "January 2026", text: `Kaleb and Knott's Tree Services are TOP TIER. From the first message to the final cleanup, everything was flawless. Kaleb took down two trees in my backyard quickly, safely, and with serious skill — zero stress on my end. The yard was left spotless, like the trees were never even there. Professional, reliable, and clearly knows his stuff. If you need tree work done, stop searching and call Knott's Tree Services. Highly recommend!` },
  { name: "Johnnie Gauthier", date: "January 2026", text: `Kaleb and his committed crew came and dropped an ash tree that towered my 2 story home. The ash tree was maybe 8-12ft away from my house with a power line in between them. They did a great job!` },
  { name: "Buddy Smith", date: "January 2026", text: `The absolute best in the business. I would highly recommend them!` },
  { name: "Helen Hartjen", date: "December 2025", text: `Show up promptly, work hard and fast, clean up after the job is done, and are courteous and all-around great people.` },
  { name: "Kristina LaRay Varner", date: "December 2025", text: `He was good and quick about getting our tree down that was leaning on our house and our neighbor's house. It took them about half a day to get it all done, but I would recommend him to do your tree services. I don't think I'm going to go with another tree service but them.` },
  { name: "Katie Teter", date: "December 2025", text: `Kaleb did a great job blading my grandma's driveway. She really needed it done and we are thankful he was able to do it for her! Thanks again!!` },
  { name: "Dinisha Borders", date: "October 2025", text: `Crew did an amazing job cutting down a large ash tree with a power line between it. Workers were all friendly and professional. They cleaned up so well you can't hardly tell there was even a tree there. Highly recommend!!` },
  { name: "Clarissa Jackson", date: "October 2025", text: `I had a great experience with K Knott Tree Services! They are very knowledgeable and friendly! After they cut down that tree, they cleaned up the mess nicely!` },
  { name: "Mary L Battin", date: "October 2025", text: `These guys did an amazing job. They cleaned everything up. I recommend these guys 1000%. What a great service.` },
  { name: "Jenni Licht", date: "September 2025", text: `This crew is always ready to do work and they do a wonderful job! We have had them come to our home and take out trees twice now and they get things done quick!` },
  { name: "Rob Liese", date: "August 2025", text: `Kaleb and the guys showed up for an estimate and ended up doing the job for a very generous deal since I am a disabled veteran. I not only recommend them to everyone, but they go above and beyond to help us veterans.` },
  { name: "Fred Bechtel", date: "July 2025", text: `He truly is one of the most upfront, honest, and professional people I have ever met. I would recommend him anytime.` },
  { name: "Michelle Sutch", date: "July 2025", text: `I've used Kaleb and his crew a few times over the last several years. First to trim a few trees. Second time to cut down a tree and grind the stump. And most recently, to clean up a large limb after a storm. Communication and punctuality are huge for me and they never disappoint! Crew is friendly and knowledgeable and they def go above and beyond! Cannot recommend this business more!! Thank you!!!` },
  { name: "Patricia Campbell", date: "July 2025", text: `They took down 2 large oak trees & trimmed up 2 maples. Outstanding job! Very professional and did a wonderful job cleaning up & with everything! Highly recommend them! Honest, polite and fair pricing! Thank you! Appreciated so much!` },
  { name: "Denise Schisler", date: "July 2025", text: `K. Knott LLC removed three large trees near power lines and my house, doing an excellent job with take down, stump grinding, and cleanup. I highly recommend them.` },
  { name: "Brittany Esry", date: "July 2025", text: `Knott Tree Services cut a tree down for us and we couldn't have been more satisfied - we didn't even need to be present, they got it all taken care of & fully trusted! We found out about them via our next door neighbor who was getting their tree cut down and we've seen them in and around our neighborhood since. Highly recommend.` },
  { name: "Ronny N Rene Smith", date: "June 2025", text: `Kaleb and his crew gave a very reasonable estimate on grinding out my stump and came the next day to do the job. The guys were very professional and did a thorough job. They came back in a couple of days to do the cleanup as we had agreed and did an outstanding job of it. Definitely recommend K. Knott tree service.` },
  { name: "Sheryl Baker", date: "May 2025", text: `The crew from K. Knott Tree Service removed two trees from my yard. They worked efficiently and precisely, and I cannot say enough for their cleanup work. They didn't leave a single stick! I would give them ten stars if I could. I couldn't be more satisfied with their work and highly recommend them!` },
  { name: "Donald Ross", date: "May 2025", text: `The guys were very knowledgeable, very courteous, did a wonderful job cleaning up. I highly recommend them. Thanks again guys.` },
  { name: "Travis A. Brobst", date: "May 2025", text: `Kaleb is quick and efficient. He delivers and gets things done. You don't have to worry about anything being missed. His prices are reasonable compared to most tree companies. I look forward to doing business again with him in the future.` },
  { name: "Nate Lewis Maxon", date: "April 2025", text: `Came out and gave us an extremely reasonable quote for removing 11 trees off our property and completed the job the same day.` },
  { name: "Bob Cox", date: "March 2025", text: `I have worked with them twice. They are quick and communicate well. Both jobs were close to the house and other plants. Nothing damaged. Thank you all for the good work.` },
  { name: "Jeanie Moen", date: "March 2025", text: `We got our estimate yesterday, and then they came out and cut our big oak tree in our front yard down the next day. They did this in a timely manner and they use safety precautions.` },
  { name: "Sara Douglas", date: "March 2025", text: `Thank you to Kaleb for getting rid of our big tree safely. Highly recommend him for a job well done.` },
  { name: "Laci Tillman", date: "March 2025", text: `Highly recommend Kaleb Knott for all your tree service needs. Communication and consistent follow-through are crucial to owning a small business. Kaleb did just that! I only had to call him one time. He came by, gave me a quote and immediately put me on his schedule. Showed up when he said he would, completed the job in a timely manner, and even cleaned up the mess!` },
  { name: "Ryne Watts", date: "March 2025", text: `Got the bid on Thursday. Serviced on Friday in strong wind, mature trees close to the house, and the crew made quick work of them for me. Very satisfied!` },
  { name: "Rondi Lynne", date: "March 2025", text: `Kaleb and his crew were on time, fast and efficient. They did a fantastic job at a very reasonable price. Literally between the bid, the suggestions on what needed done, to the cut, grind and clean up all within 3 days! Would recommend them as one of the best!` },
  { name: "Alicia Winegar-Edgar", date: "January 2025", text: `I called for an estimate, so nice and prompt. Pulled a tree off another to buy me some more time. I appreciate you so much! Thank you!` },
  { name: "John Minnis", date: "October 2024", text: `Hired them to remove a few trees & clean a few up & they were quick, reliable & easy to work with, greatly appreciate them & definitely will let anyone know who needs tree service about these guys! Best in the business!` },
  { name: "Tim George", date: "September 2024", text: `This is a great group to work with. They recently removed 4 trees off my property. They were fast, efficient and did it at a very fair price.` },
  { name: "Beth Francisco", date: "July 2024", text: `We hired K Knott LLC to remove a very large tree close to power lines. They showed up fast, it was down very quickly, with precision, and clean up was immaculate. Highly recommend them.` },
  { name: "Alyssa Black", date: "April 2024", text: `These guys knocked it out of the park. Fast working, super friendly and well priced. 10/10 will recommend them to anyone. They prioritized everyone's safety as well as cleaned up very well after dropping the tree, reseeded the yard and laid straw. Everything was done very well.` },
  { name: "Tyson Burrus", date: "July 2023", text: `Had a large tree cut down, hauled off, stump ground down, and cleaned up in 1 day! And they did some work for my neighbor too at the same time! Fantastic job! Thank you!` },
  { name: "Spencer Gordon", date: "June 2023", text: `Very efficient and super easy to work with. I would highly recommend them to anyone. Great price and great work!` },
  { name: "Marissa Schmit", date: "April 2023", text: `I had struggled to find someone local and to respond. I placed a post on my local Facebook page and within minutes Kaleb messaged me, commented and I was able to call him. He came out and quoted us that day! He was reliable, dependable, friendly and knowledgeable! He made this process a breeze! I have recommended him to a few people already because it was such a pleasure to have Kaleb and his team member doing the job!` },
  { name: "Jarrett Garber", date: "July 2022", text: `Kaleb and his crew did a stupendous job removing our trees. They had the utmost respect for our property and were able to accomplish the unbelievable task of dropping a massive sycamore right next to the house. I highly recommend!` }
];
